default_language_version:
    python: python3.10
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    # - id: trailing-whitespace
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-toml
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: check-json
    # - id: check-added-large-files
# https://pre-commit.com/hooks.html
- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.5.3
  hooks:
    - id: commitizen
      stages: [commit-msg]
      additional_dependencies: [typing-extensions]
- repo: https://github.com/ambv/black
  rev: 23.7.0
  hooks:
    - id: black

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.982
#   hooks:
#     - id: mypy
#       # args: [--ignore-missing-imports]
#       additional_dependencies: [pyside6, types-Deprecated, types-docutils, types-orjson, types-toml,  types-typed-ast, types-requests, types-python-dateutil]
#       exclude: '(sciscintilla)\.py'
